apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-server
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-server
    spec:
      containers:
      - image: spring-6-auth-server:0.0.1-SNAPSHOT
        name: spring-6-auth-server
        env:
          - name: SERVER_ISSUER
            value: auth-server
          - name: SERVER_PORT
            value: "9000"
        resources: {}
status: {}
