apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:16
        name: postgresql
        env:
          - name: POSTGRES_USER
            value: restadmin
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: restdb
        resources: {}
status: {}
