apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: reactive-mongo
  name: reactive-mongo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reactive-mongo
  clusterIP: None
status:
  loadBalancer: {}
